### ISSUE TITLE
Возможность удаления пользователя

### ISSUE THREAD

**Issue by sergey-shadrin** [sergey-shadrin/Symfony_project#8]
Обязательно перед удалением показывать попап с предупреждением.
Удаление возможно
1) из списка пользователей
2) со страницы редактирования пользователя (кнопка удалить)

**Comment by vadimDol** [comment]
lib/model/UserPeer.php:17
Сложноватый способ удаления одного пользователя.
Он больше подходил бы для случая с удалением нескольких пользователей по определённому признаку

Можно сделать следующее:
1) Получить объект User по логину
2) В случае, если объект User получен, вызвать у него метод delete.
